spring.application.name=spring-project-14aprel

logging.file.path=logs

# spring.datasource.url=jdbc:mysql://localhost:3307/educore
spring.datasource.url=jdbc:mysql://localhost:3307/computershopping_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=omar2012896363

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2
# spring.datasource.url=jdbc:h2:mem:test
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=root
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always

jwt.secret = a72020494175d0f4524bb7a33547bc5e58ae0a12186ebbc60151f66e510fd2e4