spring.application.name=spring-project-14aprel

logging.file.path:logs

# spring.datasource.url=jdbc:mysql://localhost:3307/computershopping_db
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=root
spring.datasource.password=omar2012896363

spring.jpa.hibernate.ddl-auto=update